version: "3.7"

x-container-common: &container-common
  networks:
    - vault
    
services:
  vault:
    <<: *container-common
    image: library/vault:1.6.0
    restart: ${CONTAINER_RESTART-on-failure}
    tty: true
    cap_add:
      - IPC_LOCK
    volumes:
      - ./assets/config.hcl:/vault/config.hcl:ro
      - ./build/bin/orchestrate-hashicorp-vault-plugin:/vault/plugins/orchestrate
    entrypoint: vault server -config=/vault/config.hcl
    ports:
      - 8200:8200

  vault-init:
    <<: *container-common
    build: ./assets
    environment:
      VAULT_ADDR: http://vault:8200
      PLUGIN_FILE: /vault/plugins/orchestrate
    restart: "no"
    volumes:
      - ./build/bin/orchestrate-hashicorp-vault-plugin:/vault/plugins/orchestrate
      - ./assets/init.sh:/init.sh
    depends_on:
      - vault
    command: sh /init.sh

networks:
  vault:
    driver: bridge
